name: Create scratch org for PR
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  # Allow creating comments
  pull-requests: write

env:
  SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
  SF_JWT_SECRET_KEY: ${{ secrets.SF_JWT_SECRET_KEY }}
  SF_DEVHUB_USERNAME: ${{ secrets.SF_DEVHUB_USERNAME }}
  SFDX_VERSION: 2.9.8

jobs:
  gen_username:
    name: Generate scratch org username
    runs-on: ubuntu-latest
    outputs:
      username: pull-request-${{ steps.get_issue_number.outputs.result }}@scratch-ci.com
    steps:
      - name: Get PR number
        uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

  delete:
    name: Delete PR scratch org
    if: ${{ github.event.action == 'reopened' || github.event.action == 'closed' }}
    needs: gen_username
    runs-on: ubuntu-latest
    env:
      SCRATCH_USERNAME: ${{ needs.gen_username.outputs.username }}
    steps:
      ############## Setup ##############
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install sfdx
        run: npm install --global @salesforce/cli@${SFDX_VERSION}

      - name: Authenticate
        # Authenticate to both devhub and scratch org so we can delete the scratch org
        run: |
          echo "${SF_JWT_SECRET_KEY}" > server.key
          sf org login jwt --username=${SF_DEVHUB_USERNAME} --jwt-key-file server.key --client-id=${SF_CONSUMER_KEY} --set-default-dev-hub
          sf org login jwt --username=${SCRATCH_USERNAME} --jwt-key-file server.key --client-id=${SF_CONSUMER_KEY} --set-default

      ############## Delete ##############

      - name: Delete existing PR scratch org
        # Attempt to delete it, but don't fail if it doesn't exist
        run: sf org delete scratch --no-prompt || true

  create:
    name: Create PR scratch org
    # Only run on PR open or reopen.
    # We need the "success()" part so the job runs even when the previous job is skipped.
    if: ${{ (success() && github.event.action != 'closed') || github.event.action == 'opened' || github.event.action == 'reopened' }}
    needs:
      - delete
      - gen_username
    runs-on: ubuntu-latest
    env:
      SCRATCH_USERNAME: ${{ needs.gen_username.outputs.username }}
    steps:
      ############## Setup ##############
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-npmcache-sfdx-${SFDX_VERSION}
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sfdx
        run: npm install --global @salesforce/cli@${SFDX_VERSION}

      - name: Authenticate
        run: |
          echo "${SF_JWT_SECRET_KEY}" > server.key
          sf org login jwt --username=${SF_DEVHUB_USERNAME} --jwt-key-file server.key --client-id=${SF_CONSUMER_KEY} --set-default-dev-hub

      ############## Create ##############

      - name: Create scratch org
        run: sf org create scratch --json --edition=developer --username=${SCRATCH_USERNAME} --set-default --duration-days=14 | jq

      - name: Get login info
        id: get_login_info
        run: |
          data="$(sf org open --json --url-only)"
          echo username=$(echo $data | jq -r .result.username) >> "$GITHUB_OUTPUT"
          echo url=$(echo $data | jq -r .result.url) >> "$GITHUB_OUTPUT"
          echo id=$(echo $data | jq -r .result.orgId) >> "$GITHUB_OUTPUT"

      - name: Comment login url
        uses: actions/github-script@v6
        env:
          ORG_USERNAME: ${{ steps.get_login_info.outputs.username }}
          ORG_URL: ${{ steps.get_login_info.outputs.url }}
          ORG_ID: ${{ steps.get_login_info.outputs.id }}
        with:
          script: |
            const { ORG_USERNAME, ORG_URL, ORG_ID } = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🚀 **Scratch org created!**
               - Org ID: ${ORG_ID}
               - Username: ${ORG_USERNAME}
               - Link: ${ORG_URL}
              
              **Instructions**
               - Use it perform tests and QA
               - Pushes to this PR will be deployed automatically
               - It'll be deleted automatically after 14 days or when the PR is closed`
            })

  deploy:
    name: Deploy to PR scratch org
    # Only run on PR sync (i.e. new commits pushed to PR)
    if: ${{ github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    needs:
      - gen_username
    env:
      SCRATCH_USERNAME: ${{ needs.gen_username.outputs.username }}
    steps:
      ############## Setup ##############
      - uses: actions/checkout@v4
      # - uses: actions/cache@v3
      #   with:
      #     path: "~/.npm"
      #     key: ${{ runner.os }}-npmcache-sfdx-${SFDX_VERSION}
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: print node_modules location
        run: npm root -g

      - name: Install sfdx
        run: npm install --global @salesforce/cli@${SFDX_VERSION}

      - name: Authenticate
        run: |
          echo "${SF_JWT_SECRET_KEY}" > server.key
          sf org login jwt --username=${SCRATCH_USERNAME} --jwt-key-file server.key --client-id=${SF_CONSUMER_KEY} --set-default

      ############## Deploy ##############

      - name: Deploy source
        run: sf project deploy start

      - name: Comment deployment
        uses: actions/github-script@v6
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |
            const { SHA } = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `☁️ Synced to commit ${SHA}`
            })
