#.github/workflows/main.yml
name: Deploy code to PR Scratch Org
on:
  pull_request:
    types: [synchronize]
    # branches:
    #   - "scratch-alpha/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # Allow creating comments
      issues: write
    steps:
      ############## Setup ##############
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get PR number
        uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Get scratch org alias
        id: get_org_alias
        run: echo "alias=pull-request-${{ steps.get_issue_number.outputs.result }}" >> "$GITHUB_OUTPUT"

      - name: Install sfdx
        run: npm install @salesforce/cli@2.9.8 --global

      - name: Authenticate
        env:
          SFDX_AUTH_FILE: ${{ secrets.SFDX_AUTH_FILE }}
        run: |
          echo "${SFDX_AUTH_FILE}" > auth.json
          sf org login sfdx-url --sfdx-url-file auth.json --set-default-dev-hub --set-default --alias devhub
          rm auth.json

      - name: Query existing PR scratch org
        id: query_current_org
        run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"

      ############## Deploy ##############

      - name: Abort deployment
        # Abort if the scratch org doesn't exist
        if: steps.query_current_org.outputs.status != 0
        run: |
          echo "No scratch org found for this PR. Aborting."
          exit 1

      - name: Deploy source
        run: sf project deploy start --target-org=${{ steps.get_org_alias.outputs.alias }} --dry-run

      - name: Comment deployment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '☁️ Deployed commit ${github.event.pull_request.head.sha}!'
            })
