name: Create scratch org for PR
on:
  pull_request:
    # types: [opened, reopened]
    types: [synchronize]
    # branches:
    #   - "scratch-alpha/**"

jobs:
  create:
    name: Create PR scratch org
    runs-on: ubuntu-latest
    permissions:
      # Allow creating comments
      issues: write
    steps:
      ############## Setup ##############
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get PR number
        uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Get scratch org alias
        id: get_org_alias
        run: echo "alias=pull-request-${{ steps.get_issue_number.outputs.result }}" >> "$GITHUB_OUTPUT"

      - name: Install sfdx
        run: npm install @salesforce/cli@2.9.8 --global

      - name: Authenticate
        env:
          SFDX_AUTH_FILE: ${{ secrets.SFDX_AUTH_FILE }}
        run: |
          echo "${SFDX_AUTH_FILE}" > auth.json
          sf org login sfdx-url --sfdx-url-file auth.json --set-default-dev-hub --set-default --alias devhub
          rm auth.json

      - name: Query existing PR scratch org
        id: query_current_org
        run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"

      ############## Create ##############

      - name: Delete existing PR scratch org
        # Do nothing if the scratch org doesn't exist
        if: steps.query_current_org.outputs.status == 0
        run: sf org delete scratch --target-org=${{ steps.get_org_alias.outputs.alias }} --no-prompt

      - name: Create scratch org
        id: create_org
        run: echo 'data=$(sf org create scratch --json --edition=developer --alias=${{ steps.get_org_alias.outputs.alias }} --set-default --duration-days=14)' >> "$GITHUB_OUTPUT"

      - name: Deploy source
        run: sf project deploy start --target-org=${{ steps.get_org_alias.outputs.alias }} --dry-run

      - name: Comment login url
        env:
          ORG_USERNAME: ${{ fromJSON(steps.create_org.outputs).username }}
          ORG_URL: ${{ fromJSON(steps.create_org.outputs).href }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '### 🚀 **Scratch org created!**\n\n - Username: ${ORG_USERNAME}\n - Link: ${ORG_URL}\n\n**Instructions**\n - Use it perform tests and QA\n - Pushes to this PR will be deployed automatically\n - It'll be deleted automatically after 14 days or when the PR is closed'
            })
